// Generated by https://quicktype.io

export interface Catalogos {
  Catalog: Catalog;
}
 
export interface Catalog {
  cil: Cil[];
  inspecciones : Inspecciones[];
  entregas: Entregas[];
  acciones: Acciones[];
  banios: Banio[];
  iniciales_locos: InicialesLoco[];
  locomotoras: Locomotora[];
  mantenedores: Mantenedore[];
  empleados: Empleado[];
  funciones: Funcione[];
}  

export interface Cil {
  id_cil:              string;
  desc_cil:            string;
  activo:              string;
  fecha_registro:      Date;
  fecha_actualizacion: Date;
  PUESTO_TRABAJO:      string|null;
}

export interface Inspecciones {
  id_tipo_inspeccion:   number;
  tipo_inspeccion:      string;
  desc_tipo_inspeccion: string;
  tiempo_meta:          number;
  activo:               string;
  fecha_registro:       string;
  fecha_actualizacion:  string;
}

export interface Entregas {
  id_tipo_entrega:     number;
  desc_tipo_entrega:   string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Acciones {
  id_accion:           number;
  desc_accion:         string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Banio {
  id_banio:            number;
  desc_banio:          string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface InicialesLoco {
  id_inicial_loco:     number;
  desc_inicial_loco:   string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Locomotora {
  id_loco:             number;
  desc_loco:           string;
  fk_mantenedor:       number;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Mantenedore {
  id_mantenedor:       number;
  desc_mantenedor:     string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Empleado {
  id_empleado:         number;
  nombre_empl:         string;
  apellido_empl:       string;
  fk_funcion_empl:     number;
  acceso_cil:          string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Funcione {
  id_funcion:          number;
  desc_funcion:        string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}
