// Generated by https://quicktype.io

export interface Catalogos {
  Catalog: Catalog;
}
 
export interface Catalog {
  cil: Cil[];
  inspecciones : Inspecciones[];
  entregas: Entregas[];
  acciones: Acciones[];
  banios: Banio[];
}  

export interface Cil {
  id_cil:              string;
  desc_cil:            string;
  activo:              string;
  fecha_registro:      Date;
  fecha_actualizacion: Date;
  PUESTO_TRABAJO:      string|null;
}

export interface Inspecciones {
  id_tipo_inspeccion:   number;
  tipo_inspeccion:      string;
  desc_tipo_inspeccion: string;
  tiempo_meta:          number;
  activo:               string;
  fecha_registro:       string;
  fecha_actualizacion:  string;
}

export interface Entregas {
  id_tipo_entrega:     number;
  desc_tipo_entrega:   string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Acciones {
  id_accion:           number;
  desc_accion:         string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}

export interface Banio {
  id_banio:            number;
  desc_banio:          string;
  activo:              string;
  fecha_registro:      string;
  fecha_actualizacion: string;
}




