// Generated by https://quicktype.io

export interface CatalogoCil {
    Catalog: Catalog;
}

export interface Catalog {
    datos: Cil[];
}

export interface Cil {
    id_cil:              string;
    desc_cil:            string;
    activo:              string;
    fecha_registro:      string;
    fecha_actualizacion: string;
    PUESTO_TRABAJO:      string;
}
