// Generated by https://quicktype.io

export interface Calogos {
    Catalog: Catalog;
}

export interface Catalog {
    banios: Banio[];
}

export interface Banio {
    id_banio:            number;
    desc_banio:          string;
    activo:              string;
    fecha_registro:      string;
    fecha_actualizacion: string;
}
