// Generated by https://quicktype.io

export interface Token {
  token: string;
}

export interface Catalogos {
  Catalog: Catalog;
}

export interface Catalog {
  cil: Cil[];
}

export interface Cil {
  id_cil: string;
  desc_cil: string;
  activo: string;
  fecha_registro: Date;
  fecha_actualizacion: Date;
  PUESTO_TRABAJO: string | null;
}


export interface TokenData {
  username: string;
  nbf: number;
  exp: number;
  iat: number;
  iss: string;
  aud: string;
}